services:

  postgres:
    image: postgres:16
    container_name: cppjudge-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cppjudge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cppjudge-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
